### ISSUE TITLE
Error: Bidder Pot Token Must be a new account when using instant sale

### ISSUE THREAD

**Issue by darainj** [metaplex-foundation/js-deprecated#192]
Steps to reproduce:
1. call instantSale(with appropriate params)

`SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 5: custom program error: 0x1f
    at Connection.sendEncodedTransaction (/Users/darashahriari/injective/sol_secret_bot/node_modules/@solana/web3.js/lib/index.cjs.js:6591:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (/Users/darashahriari/injective/sol_secret_bot/node_modules/@solana/web3.js/lib/index.cjs.js:6550:20) {
  logs: [
    'Program 11111111111111111111111111111111 invoke [1]',
    'Program 11111111111111111111111111111111 success',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]',
    'Program log: Instruction: InitializeAccount',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 3392 of 200000 compute units',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success',
    'Program 11111111111111111111111111111111 invoke [1]',
    'Program 11111111111111111111111111111111 success',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]',
    'Program log: Instruction: InitializeAccount',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 3391 of 200000 compute units',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]',
    'Program log: Instruction: Approve',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2025 of 200000 compute units',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success',
    'Program auctxRXPeJoc4817jDhf4HbjnhEcr1cCXenosMhK5R8 invoke [1]',
    'Program log: + Processing PlaceBid',
    'Program log: Transfer 1454640 lamports to the new account',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program log: Allocate space for the account',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program log: Assign the account to the owning program',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program log: Completed assignation!',
    'Program log: Transfer 1566000 lamports to the new account',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program log: Allocate space for the account',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program log: Assign the account to the owning program',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program log: Completed assignation!',
    'Program log: assert_uninitialized',
    'Program log: Bidder Pot Token Must be a new account',
    'Program log: Custom program error: 0x1f',
    'Program auctxRXPeJoc4817jDhf4HbjnhEcr1cCXenosMhK5R8 consumed 46562 of 200000 compute units',
    'Program auctxRXPeJoc4817jDhf4HbjnhEcr1cCXenosMhK5R8 failed: custom program error: 0x1f'
  ]`

**Comment by bassmoneynft** [comment]
This is an open PR that fixes this: https://github.com/metaplex-foundation/js/pull/172 as discussed in  https://github.com/metaplex-foundation/js/issues/155
