### ISSUE TITLE
Invalid owner

### ISSUE THREAD

**Issue by Rasfuranku** [metaplex-foundation/js-deprecated#39]
I am trying to set up the project and when getting the metadata I always got the following error.

Tried on different environments with the same result.

Happening in both v2.0.0, v2.0.1 versions.

```
Error: Invalid owner

    at ERROR_INVALID_OWNER (node_modules\@metaplex\js\api\src\errors.ts:17:10)
    at new Metadata (node_modules\@metaplex\js\api\src\programs\metadata\accounts\Metadata.ts:106:13)
    at Function.<anonymous> (sloth-combiner\node_modules\@metaplex\js\api\src\Account.ts:30:12)
    at Generator.next (<anonymous>)
    at fulfilled (sloth-combiner\node_modules\@metaplex\js\lib\index.cjs.js:101:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by WrRaThY** [comment]
@m-sebastiyan any hints on getting the `Metadata address` based on the `mint address`?

**Comment by hwsimmons17** [comment]
That is so incredibly helpful!!! Much better than the jenky code I was running earlier! Thank you so much

**Comment by jhubbardsf** [comment]
> @m-sebastiyan Is there a repo/branch for the in-progress docs? Are you keen on getting help with that?

Am I missing something or is this still not covered anywhere in the docs?
